name: ci

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-14, ubuntu-22.04]
        node: ['14.21.3', '18', '20', '22']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
